version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: academic_docs_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  app:
    build: .
    container_name: academic_docs_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/mongo"
