version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: academic_docs_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - academic_net

  app:
    build: .
    container_name: academic_docs_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - npm_cache:/app/.npm-cache
    depends_on:
      - mongodb
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  init_admin_user:
    image: node:16-alpine
    container_name: init_admin_user
    volumes:
      - ./mongo-init:/usr/src/app
    working_dir: /usr/src/app
    command: ["/bin/sh", "-c", "npm install bcrypt && node init-user.js"]
    depends_on:
      - mongodb
    networks:
      - academic_net

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/mongo"
  npm_cache:

networks:
  academic_net: